# Keyb bindings ================================================================
# change prefix key
set -g prefix C-a
# split pane shortcuts
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
# move pane shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize pane shortcuts
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# Enable vi keys in copy mode
setw -g mode-keys vi
bind v copy-mode
# copy mode key bindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi Escape send-keys -X clear-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel
# paste
bind p paste-buffer
# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded the config file!"

# General settings ==============================================================
# copy to system clipboard
if-shell -b '[ "$(uname)" = "Darwin" ]' {
  set -s copy-command "pbcopy"
}
if-shell -b '[ "$(uname)" = "Linux" ]' {
  set -s copy-command "xsel --clipboard --input"
}
# disable automatic window resize
setw -g aggressive-resize off
# enable mouse operator
set-option -g mouse on
# color support in tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# status bar ==================================================================
set -g status-position bottom
set -g status-right "%Y-%m-%d %H:%M:%S"
set -g status-interval 1
set -g status-left "[#S: #h]"
set -g status-left-length 100
set -g window-status-format ""
set -g window-status-current-format ""
set -g status-style "fg=#ffffff,bg=#333333,dim"
