# Keyb bindings ================================================================
# change prefix key
set -g prefix C-a
# split pane shortcuts
bind | split-window -h -c '#{pane_current_path}'
bind - split-window -v -c '#{pane_current_path}'
# move pane shortcuts
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# resize pane shortcuts
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5
# windows
# create new window
bind t new-window -c '#{pane_current_path}'
# switch to previous/next window
bind [ previous-window
bind ] next-window
# switch to specific window
bind 0 select-window -t :0
bind 1 select-window -t :1
bind 2 select-window -t :2
bind 3 select-window -t :3
bind 4 select-window -t :4
bind 5 select-window -t :5
bind 6 select-window -t :6
bind 7 select-window -t :7
bind 8 select-window -t :8
bind 9 select-window -t :9

# Enable vi keys in copy mode
setw -g mode-keys vi
bind v copy-mode
# copy mode key bindings
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi V send-keys -X select-line
bind -T copy-mode-vi Escape send-keys -X clear-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel
# paste
bind p paste-buffer
# reload config
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded the config file!"

# General settings ==============================================================
# copy to system clipboard
if-shell -b '[ "$(uname)" = "Darwin" ]' {
  set -s copy-command "pbcopy"
}
if-shell -b '[ "$(uname)" = "Linux" ]' {
  set -s copy-command "xsel --clipboard --input"
}
# disable automatic window resize
setw -g aggressive-resize off
# enable mouse operator
set-option -g mouse on
# renumber windows when one is closed
set -g renumber-windows on
# start window numbering from 1
set -g base-index 1
# disable automatic renaming of windows
set -g allow-rename off
# color support in tmux
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# status bar ==================================================================
set -g status-position bottom
set -g status-right " %Y-%m-%d  %H:%M:%S"
set -g status-interval 1
if-shell -b '[ "$(uname)" = "Darwin" ]' {
    set -g status-left "#[fg=#aeaed2,bg=#000000]░▒▓#[fg=#000000,bg=##aeaed2]  #[fg=#aeaed2,bg=#000000]#[default] #S "
}
if-shell -b '[ "$(uname)" = "Linux" ]' {
    set -g status-left "#[fg=#aeaed2,bg=#000000]░▒▓#[fg=#000000,bg=##aeaed2]  #[fg=#aeaed2,bg=#000000]#[default] #S "
}
set -g status-left "[#h: #S] "
set -g status-left-length 100
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-current-style "fg=#ffffff,bg=#555555,bold"
set -g status-style "fg=#ffffff,bg=#333333,dim"

