#!/bin/bash

SLEEP_SECOND=0.1

multiplexer=$(detect_multiplexer)

pane_id=$1
message=$2

if [[ $multiplexer == "Zellij" ]]; then
    zellij action write-chars --pane-id "${pane_id}" "${message}"
    sleep ${SLEEP_SECOND}
    zellij action write --pane-id "${pane_id}" 13
elif [[ $multiplexer == "Tmux" ]]; then
    tmux send-keys -t "${pane_id}" "$message"
    sleep ${SLEEP_SECOND}
    tmux send-keys -t "${pane_id}" Enter
elif [[ $multiplexer == "WezTerm" ]]; then
    wezterm cli send-text --pane-id "${pane_id}" "${message}"
    sleep ${SLEEP_SECOND}
    wezterm cli send-text --pane-id "${pane_id}" --no-paste $'\r'
else
  echo "Error: Unsupported multiplexer." >&2
  exit 1
fi
