# yazi config file
[mgr]
sort_by = "extension"
show_hidden = true

[opener]
edit = [
	{ run = "${EDITOR:-nvim} %s", desc = "$EDITOR", for = "unix", block = true },
	{ run = 'nvim %*', desc = "nvim", for = "windows", block = true },
]

[[plugin.prepend_fetchers]]
id    = "mime"
group = "mime"
url   = "local://*"
run   = "mime-ext.local"
prio  = "high"

[[plugin.prepend_fetchers]]
id    = "mime"
group = "mime"
url   = "remote://*"
run   = "mime-ext.remote"
prio  = "high"
